import React, { useMemo, useState } from 'react';
import type { Dokument, FinanzEintrag, Handwerker, KalenderTermin, KontaktPerson, Liegenschaft, Schluessel } from '../../types/domain.types';

type Setter<T> = React.Dispatch<React.SetStateAction<T[]>>;

const page: React.CSSProperties = { display: 'flex', flexDirection: 'column', gap: 18 };
const title: React.CSSProperties = { margin: 0, fontSize: 26, color: '#0f172a' };
const subtitle: React.CSSProperties = { margin: '6px 0 0', color: '#64748b', fontSize: 14 };
const grid: React.CSSProperties = { display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(260px, 1fr))', gap: 16 };
const card: React.CSSProperties = { background: '#fffaf3', border: '1px solid #eadfce', borderRadius: 18, padding: 18, boxShadow: '0 8px 24px rgba(15,23,42,.05)' };
const input: React.CSSProperties = { width: '100%', padding: '10px 12px', border: '1px solid #d7cdbc', borderRadius: 10, background: '#fff', boxSizing: 'border-box' };
const btn: React.CSSProperties = { border: 'none', background: '#2f6fed', color: '#fff', borderRadius: 10, padding: '10px 14px', fontWeight: 700, cursor: 'pointer' };
const lightBtn: React.CSSProperties = { border: '1px solid #d7cdbc', background: '#fffaf3', color: '#0f172a', borderRadius: 10, padding: '10px 14px', fontWeight: 700, cursor: 'pointer' };

function Header({ name, text, action }: { name: string; text: string; action?: React.ReactNode }) {
  return <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', gap: 16 }}><div><h1 style={title}>{name}</h1><p style={subtitle}>{text}</p></div>{action}</div>;
}
function Pill({ children, tone = 'blue' }: { children: React.ReactNode; tone?: 'blue'|'green'|'orange'|'red'|'gray' }) {
  const colors = { blue: ['#dbeafe','#1d4ed8'], green: ['#dcfce7','#15803d'], orange: ['#ffedd5','#c2410c'], red: ['#fee2e2','#b91c1c'], gray: ['#f1f5f9','#475569'] } as const;
  return <span style={{ background: colors[tone][0], color: colors[tone][1], padding: '5px 9px', borderRadius: 999, fontSize: 12, fontWeight: 700 }}>{children}</span>;
}
function personName(liegenschaften: Liegenschaft[], id?: string) { for (const l of liegenschaften) { const p = l.personen.find(x => x.id === id); if (p) return p.name; } return 'Nicht zugeordnet'; }
function liegName(liegenschaften: Liegenschaft[], id: string) { return liegenschaften.find(l => l.id === id)?.name ?? 'Unbekannte Liegenschaft'; }
function allPersons(liegenschaften: Liegenschaft[]): (KontaktPerson & { liegenschaftId: string; liegenschaftName: string })[] { return liegenschaften.flatMap(l => l.personen.map(p => ({ ...p, liegenschaftId: l.id, liegenschaftName: l.name }))); }

export function DokumenteView({ dokumente, setDokumente, liegenschaften }: { dokumente: Dokument[]; setDokumente: Setter<Dokument>; liegenschaften: Liegenschaft[] }) {
  const [suche, setSuche] = useState('');
  const [form, setForm] = useState({ titel: '', kategorie: 'Sonstiges', liegenschaftId: liegenschaften[0]?.id ?? '', personId: '', dateiname: '' });
  const gefiltert = dokumente.filter(d => `${d.titel} ${d.kategorie} ${d.jahr} ${d.volltext}`.toLowerCase().includes(suche.toLowerCase()));
  const gruppiert = gefiltert.reduce<Record<string, Dokument[]>>((acc, d) => { const key = `${d.jahr} · ${d.kategorie}`; (acc[key] ??= []).push(d); return acc; }, {});
  const save = () => { if (!form.titel.trim()) return; setDokumente(prev => [{ id: crypto.randomUUID(), titel: form.titel, kategorie: form.kategorie as Dokument['kategorie'], liegenschaftId: form.liegenschaftId, personId: form.personId || undefined, jahr: new Date().getFullYear(), dateiname: form.dateiname || `${form.titel}.pdf`, version: 1, freigabeStatus: 'Kunde sichtbar', hochgeladenAm: new Date().toISOString(), volltext: form.titel }, ...prev]); setForm({ ...form, titel: '', dateiname: '' }); };
  return <div style={page}><Header name="Dokumentenmanagement" text="Mietverträge, Hausordnungen, Rechnungen, Abnahmeprotokolle, Pläne und Schlüsselquittungen mit Versionierung und Kundenfreigabe." action={<input style={{...input, width: 320}} placeholder="Volltextsuche ..." value={suche} onChange={e=>setSuche(e.target.value)} />} />
    <div style={card}><h3>Dokument hochladen / erfassen</h3><div style={grid}><input style={input} placeholder="Titel" value={form.titel} onChange={e=>setForm({...form,titel:e.target.value})}/><select style={input} value={form.kategorie} onChange={e=>setForm({...form,kategorie:e.target.value})}>{['Mietvertrag','Hausordnung','Versicherung','Rechnung','Abnahmeprotokoll','Plan','Schlüsselquittung','Sonstiges'].map(x=><option key={x}>{x}</option>)}</select><select style={input} value={form.liegenschaftId} onChange={e=>setForm({...form,liegenschaftId:e.target.value})}>{liegenschaften.map(l=><option key={l.id} value={l.id}>{l.name}</option>)}</select><select style={input} value={form.personId} onChange={e=>setForm({...form,personId:e.target.value})}><option value="">Intern / keine Person</option>{allPersons(liegenschaften).filter(p=>p.liegenschaftId===form.liegenschaftId).map(p=><option key={p.id} value={p.id}>{p.name} · {p.rolle}</option>)}</select><input style={input} placeholder="PDF-Dateiname oder S3-Link" value={form.dateiname} onChange={e=>setForm({...form,dateiname:e.target.value})}/><button style={btn} onClick={save}>Speichern & für App freigeben</button></div></div>
    {Object.entries(gruppiert).map(([key, docs]) => <div key={key} style={card}><h3>{key}</h3>{docs.map(d => <div key={d.id} style={{display:'grid', gridTemplateColumns:'1fr auto auto', gap:12, padding:'12px 0', borderTop:'1px solid #eee'}}><div><b>{d.titel}</b><div style={subtitle}>{liegName(liegenschaften,d.liegenschaftId)} · {personName(liegenschaften,d.personId)} · Version {d.version}</div></div><Pill tone={d.freigabeStatus==='Kunde sichtbar'?'green':'gray'}>{d.freigabeStatus}</Pill><span>{d.dateiname}</span></div>)}</div>)}
  </div>;
}

export function KalenderView({ termine, setTermine, liegenschaften, handwerker }: { termine: KalenderTermin[]; setTermine: Setter<KalenderTermin>; liegenschaften: Liegenschaft[]; handwerker: Handwerker[] }) {
  const [lieg, setLieg] = useState(liegenschaften[0]?.id ?? '');
  const persons = allPersons(liegenschaften).filter(p=>p.liegenschaftId===lieg);
  const [form, setForm] = useState({ titel:'', typ:'Handwerkertermin', personId: persons[0]?.id ?? '', handwerkerId:'', start:'', ende:'', ort:'', sichtbarInApp:true });
  const speichern = () => { if (!form.titel || !form.start) return; setTermine(prev => [{ id: crypto.randomUUID(), titel: form.titel, typ: form.typ as KalenderTermin['typ'], liegenschaftId: lieg, personIds: form.personId ? [form.personId] : [], handwerkerId: form.handwerkerId || undefined, start: form.start, ende: form.ende || form.start, ort: form.ort || liegName(liegenschaften, lieg), beschreibung: '', erinnerungMinuten: 1440, sichtbarInApp: form.sichtbarInApp, status: 'Geplant' }, ...prev]); setForm({ ...form, titel:'' }); };
  return <div style={page}><Header name="Kalender" text="Handwerkertermine, Übergaben, Abnahmen und Eigentümerversammlungen. Sichtbare Termine erscheinen beim zugeordneten Mieter/Eigentümer in der App." />
    <div style={card}><h3>Neuen Termin erfassen</h3><div style={grid}><input style={input} placeholder="Titel" value={form.titel} onChange={e=>setForm({...form,titel:e.target.value})}/><select style={input} value={form.typ} onChange={e=>setForm({...form,typ:e.target.value})}>{['Handwerkertermin','Übergabetermin','Wohnungsabnahme','Besichtigung','Eigentümerversammlung','Sonstiges'].map(x=><option key={x}>{x}</option>)}</select><select style={input} value={lieg} onChange={e=>{setLieg(e.target.value); setForm({...form, personId:''});}}>{liegenschaften.map(l=><option key={l.id} value={l.id}>{l.name}</option>)}</select><select style={input} value={form.personId} onChange={e=>setForm({...form,personId:e.target.value})}><option value="">Keine Person</option>{persons.map(p=><option key={p.id} value={p.id}>{p.name} · {p.rolle}</option>)}</select><select style={input} value={form.handwerkerId} onChange={e=>setForm({...form,handwerkerId:e.target.value})}><option value="">Kein Handwerker</option>{handwerker.map(h=><option key={h.id} value={h.id}>{h.firma} · {h.gewerk}</option>)}</select><input style={input} type="datetime-local" value={form.start} onChange={e=>setForm({...form,start:e.target.value})}/><input style={input} type="datetime-local" value={form.ende} onChange={e=>setForm({...form,ende:e.target.value})}/><input style={input} placeholder="Ort" value={form.ort} onChange={e=>setForm({...form,ort:e.target.value})}/><label style={{display:'flex',alignItems:'center',gap:8}}><input type="checkbox" checked={form.sichtbarInApp} onChange={e=>setForm({...form,sichtbarInApp:e.target.checked})}/> In Kunden-App anzeigen</label><button style={btn} onClick={speichern}>Termin speichern</button></div></div>
    <div style={card}><h3>Terminübersicht</h3>{termine.sort((a,b)=>a.start.localeCompare(b.start)).map(t=><div key={t.id} style={{display:'grid', gridTemplateColumns:'160px 1fr auto', gap:12, padding:'14px 0', borderTop:'1px solid #eee'}}><div><b>{new Date(t.start).toLocaleDateString('de-CH')}</b><br/><span>{new Date(t.start).toLocaleTimeString('de-CH',{hour:'2-digit',minute:'2-digit'})}</span></div><div><b>{t.titel}</b><div style={subtitle}>{t.typ} · {liegName(liegenschaften,t.liegenschaftId)} · {t.personIds.map(id=>personName(liegenschaften,id)).join(', ')}</div></div><Pill tone={t.sichtbarInApp?'green':'gray'}>{t.sichtbarInApp?'App sichtbar':'Intern'}</Pill></div>)}</div>
  </div>;
}

export function HandwerkerView({ handwerker, setHandwerker }: { handwerker: Handwerker[]; setHandwerker: Setter<Handwerker> }) {
  const [firma, setFirma] = useState('');
  const add = () => { if (!firma) return; setHandwerker(prev => [{ id: crypto.randomUUID(), firma, gewerk:'Sonstiges', email:'', telefon:'', bewertung:0, einsaetze:0, durchschnittskosten:0 }, ...prev]); setFirma(''); };
  return <div style={page}><Header name="Handwerkerverwaltung" text="Handwerkerdatenbank mit Gewerken, Bewertungen, Einsatzhistorie und Durchschnittskosten." action={<><input style={{...input,width:260}} placeholder="Neue Firma" value={firma} onChange={e=>setFirma(e.target.value)}/><button style={btn} onClick={add}>Hinzufügen</button></>} /><div style={grid}>{handwerker.map(h=><div style={card} key={h.id}><h3>{h.firma}</h3><Pill>{h.gewerk}</Pill><p>{h.email}<br/>{h.telefon}</p><p>Bewertung: <b>{h.bewertung || '-'} ★</b><br/>Einsätze: <b>{h.einsaetze}</b><br/>Ø Kosten: <b>CHF {h.durchschnittskosten.toLocaleString('de-CH')}</b></p></div>)}</div></div>;
}

export function SchluesselView({ schluessel, setSchluessel, liegenschaften, handwerker, dokumente, setDokumente }: { schluessel: Schluessel[]; setSchluessel: Setter<Schluessel>; liegenschaften: Liegenschaft[]; handwerker: Handwerker[]; dokumente: Dokument[]; setDokumente: Setter<Dokument> }) {
  const [lieg, setLieg] = useState(liegenschaften[0]?.id ?? '');
  const persons = allPersons(liegenschaften).filter(p=>p.liegenschaftId===lieg);
  const [form, setForm] = useState({ bezeichnung:'', nummer:'', personId:'', handwerkerId:'', quittung:'' });
  const ausgeben = () => { if (!form.bezeichnung) return; const person = persons.find(p=>p.id===form.personId); const hw = handwerker.find(h=>h.id===form.handwerkerId); let docId: string | undefined; if (form.quittung) { docId = crypto.randomUUID(); setDokumente(prev => [{ id: docId!, liegenschaftId: lieg, personId: form.personId || undefined, titel:`Schlüsselquittung ${form.bezeichnung}`, kategorie:'Schlüsselquittung', jahr:new Date().getFullYear(), dateiname:form.quittung, version:1, freigabeStatus:'Kunde sichtbar', hochgeladenAm:new Date().toISOString(), volltext:`Schlüssel ${form.bezeichnung} ${form.nummer}` }, ...prev]); } setSchluessel(prev => [{ id: crypto.randomUUID(), liegenschaftId: lieg, personId: form.personId || undefined, handwerkerId: form.handwerkerId || undefined, bezeichnung: form.bezeichnung, nummer: form.nummer, status: (form.personId||form.handwerkerId)?'Ausgeliehen':'Verfügbar', ausgegebenAn: person?.name ?? hw?.firma, ausgegebenAm: new Date().toISOString().slice(0,10), quittungDokumentId: docId }, ...prev]); setForm({ bezeichnung:'', nummer:'', personId:'', handwerkerId:'', quittung:'' }); };
  return <div style={page}><Header name="Schlüsselverwaltung" text="Schlüsselbestand, Ausgaben/Rückgaben und Schlüsselquittungen. Quittungen werden automatisch als Kundendokument freigegeben." />
  <div style={card}><h3>Schlüssel erfassen / ausgeben</h3><div style={grid}><select style={input} value={lieg} onChange={e=>setLieg(e.target.value)}>{liegenschaften.map(l=><option key={l.id} value={l.id}>{l.name}</option>)}</select><input style={input} placeholder="Bezeichnung" value={form.bezeichnung} onChange={e=>setForm({...form,bezeichnung:e.target.value})}/><input style={input} placeholder="Schlüsselnummer" value={form.nummer} onChange={e=>setForm({...form,nummer:e.target.value})}/><select style={input} value={form.personId} onChange={e=>setForm({...form,personId:e.target.value,handwerkerId:''})}><option value="">Nicht an Mieter/Eigentümer</option>{persons.map(p=><option key={p.id} value={p.id}>{p.name} · {p.rolle}</option>)}</select><select style={input} value={form.handwerkerId} onChange={e=>setForm({...form,handwerkerId:e.target.value,personId:''})}><option value="">Nicht an Handwerker</option>{handwerker.map(h=><option key={h.id} value={h.id}>{h.firma}</option>)}</select><input style={input} placeholder="PDF Schlüsselquittung / Dateiname" value={form.quittung} onChange={e=>setForm({...form,quittung:e.target.value})}/><button style={btn} onClick={ausgeben}>Speichern</button></div></div>
  <div style={card}><h3>Schlüsselbestand</h3>{schluessel.map(k=><div key={k.id} style={{display:'grid',gridTemplateColumns:'1fr auto auto',gap:12,padding:'12px 0',borderTop:'1px solid #eee'}}><div><b>{k.bezeichnung}</b><div style={subtitle}>{liegName(liegenschaften,k.liegenschaftId)} · Nr. {k.nummer} · {k.ausgegebenAn ?? 'Verwaltung'}</div></div><Pill tone={k.status==='Verfügbar'?'green':k.status==='Ausgeliehen'?'orange':'red'}>{k.status}</Pill><span>{k.quittungDokumentId ? dokumente.find(d=>d.id===k.quittungDokumentId)?.dateiname : 'Keine Quittung'}</span></div>)}</div></div>;
}

export function FinanzenView({ finanzen, liegenschaften }: { finanzen: FinanzEintrag[]; liegenschaften: Liegenschaft[] }) {
  const sum = (status?: FinanzEintrag['status']) => finanzen.filter(f=>!status || f.status===status).reduce((a,b)=>a+b.betrag,0);
  return <div style={page}><Header name="Finanzübersicht" text="Budgets, offene Rechnungen, Unterhaltskosten und Nebenkosten pro Liegenschaft." /><div style={grid}><div style={card}><h3>Offen</h3><h2>CHF {sum('Offen').toLocaleString('de-CH')}</h2></div><div style={card}><h3>Überfällig</h3><h2>CHF {sum('Überfällig').toLocaleString('de-CH')}</h2></div><div style={card}><h3>Total erfasst</h3><h2>CHF {sum().toLocaleString('de-CH')}</h2></div></div><div style={card}>{finanzen.map(f=><div key={f.id} style={{display:'grid',gridTemplateColumns:'1fr auto auto',gap:12,padding:'12px 0',borderTop:'1px solid #eee'}}><div><b>{f.titel}</b><div style={subtitle}>{liegName(liegenschaften,f.liegenschaftId)} · {f.kategorie} · fällig {f.faelligAm}</div></div><b>CHF {f.betrag.toLocaleString('de-CH')}</b><Pill tone={f.status==='Bezahlt'?'green':f.status==='Überfällig'?'red':'orange'}>{f.status}</Pill></div>)}</div></div>;
}

export function MieterportalView({ liegenschaften, dokumente, termine }: { liegenschaften: Liegenschaft[]; dokumente: Dokument[]; termine: KalenderTermin[] }) {
  const p = allPersons(liegenschaften)[0];
  const docs = dokumente.filter(d=>d.freigabeStatus==='Kunde sichtbar' && (!d.personId || d.personId===p?.id));
  const visible = termine.filter(t=>t.sichtbarInApp && (!p || t.personIds.includes(p.id)));
  return <div style={page}><Header name="Mieter-/Eigentümerportal" text="Vorschau der Kundenansicht: Schaden melden, Dokumente herunterladen, Termine sehen und Kontaktdaten aktualisieren." /><div style={grid}><div style={card}><h3>{p?.name}</h3><p>{p?.rolle} · {p?.liegenschaftName}<br/>{p?.email}<br/>{p?.telefon}</p><button style={btn}>Neue Meldung erfassen</button></div><div style={card}><h3>Kundendokumente</h3>{docs.map(d=><p key={d.id}>📄 {d.jahr} · {d.kategorie}<br/><b>{d.titel}</b></p>)}</div><div style={card}><h3>Termine in der App</h3>{visible.map(t=><p key={t.id}>📅 {new Date(t.start).toLocaleString('de-CH')}<br/><b>{t.titel}</b></p>)}</div></div></div>;
}

export function KiView() { return <div style={page}><Header name="KI-Assistent" text="Vorbereitung für Amazon Bedrock: Schäden zusammenfassen, Handwerker vorschlagen, Offerten vergleichen und Aufträge mit Freigabe vorbereiten." /><div style={card}><h3>KI-Assistent</h3><p>Die Funktion ist vorbereitet und wird später mit echten Portal-Daten verbunden.</p><textarea style={{...input, minHeight:120}} placeholder="KI-Frage eingeben ..."/><br/><br/><button style={lightBtn}>Vorbereitet – Bedrock später aktivieren</button></div></div> }
